package user_update

const (
	FieldStatus       = "status"
	FieldRole         = "role"
	FieldFirstName    = "first_name"
	FieldLastName     = "last_name"
	FieldEmail        = "email"
	FieldBusinessName = "business_name"
	FieldPhone        = "phone"
	FieldCountry      = "country"
	FieldTimezone     = "timezone"
	FieldMemo         = "memo"
	FieldStatusField  = "field_status"
	FieldCountries    = "countries"
	FieldTimezones    = "timezones"
	FieldIsoCode2     = "iso_code_2"
	FieldName         = "name"
	FieldID           = "id"
	FieldHandle       = "handle"
	FieldRoles        = "roles"
	FieldUserRoleIDs  = "user_role_ids"
	FieldGroups       = "groups"
	FieldUserGroupIDs = "user_group_ids"
)
